version: '3'
services:
  ingest:
    restart: on-failure
    image: 'subsquid/substrate-ingest:firesquid'
    container_name: ingest
    command:
      - '-e'
      - 'wss://laguna-chain-dev.hydrogenx.live'
      - '-c'
      - '20'
      - '--out'
      - 'postgres://squid_admin:Vnzn4ygbxWnH@35.223.3.67:5432/squid_archive?sslmode=disable'
    networks:
      - squid-archive
  gateway:
    image: 'subsquid/substrate-gateway:firesquid'
    container_name: gateway
    environment:
      DATABASE_MAX_CONNECTIONS: 5
      RUST_LOG: 'actix_web=info,actix_server=info'
    command:
      - '--database-url'
      - 'postgres://squid_admin:Vnzn4ygbxWnH@35.223.3.67:5432/squid_archive?sslmode=disable'
      - '--contracts-support'
    ports:
      - '8888:8000'
    networks:
      - squid-archive
  explorer:
    image: 'subsquid/substrate-explorer:firesquid'
    container_name: explorer
    environment:
      DB_TYPE: postgres
      DB_HOST: 35.223.3.67
      DB_PORT: '5432'
      DB_NAME: squid_archive
      DB_USER: squid_admin
      DB_PASS: Vnzn4ygbxWnH
    ports:
      - '4444:3000'
    networks:
      - squid-archive
  chain-queries:
    image: 'us-docker.pkg.dev/laguna-chain/laguna-chain/chain-queries:latest'
    container_name: chain-queries
    environment:
      DB_NAME: squid_archive
      DB_HOST: 35.223.3.67
      DB_PORT: 5432
      DB_USER: squid_admin
      DB_PASSWORD: Vnzn4ygbxWnH
    ports:
      - '3050:3050'
    networks:
      - squid-archive
networks:
  squid-archive:
    name: squid-archive
